# reports/generator.py
# Generate downloadable business reports as text

from datetime import datetime


def generate_text_report(kpis, cat_data, forecasts, anomalies, diagnostics, growth_rate, industry):
    """Generate a plain text business report."""

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append("=" * 60)
    lines.append(f"  AI BUSINESS ANALYST REPORT")
    lines.append(f"  Industry: {industry}")
    lines.append(f"  Generated: {now}")
    lines.append("=" * 60)
    lines.append("")

    # KPIs
    lines.append("KEY PERFORMANCE INDICATORS")
    lines.append("-" * 40)
    for key, value in kpis.items():
        if key == 'Profit Margin':
            lines.append(f"  {key}: {value:.1%}")
        elif isinstance(value, float):
            lines.append(f"  {key}: ${value:,.2f}")
        else:
            lines.append(f"  {key}: {value}")
    lines.append("")

    # Growth Rate
    if growth_rate is not None:
        lines.append(f"Month-over-Month Growth: {growth_rate:+.1f}%")
        lines.append("")

    # Category Performance
    if cat_data is not None and not cat_data.empty:
        lines.append("CATEGORY PERFORMANCE")
        lines.append("-" * 40)
        lines.append(cat_data.to_string())
        lines.append("")

    # Forecast
    if forecasts:
        lines.append("SALES FORECAST (Next 3 Months)")
        lines.append("-" * 40)
        for i, f in enumerate(forecasts, 1):
            lines.append(f"  Month +{i}: ${f:,.2f}")
        lines.append("")

    # Anomalies
    if anomalies is not None and not anomalies.empty:
        lines.append(f"ANOMALIES DETECTED: {len(anomalies)} months")
        lines.append("-" * 40)
        lines.append(anomalies.to_string(index=False))
        lines.append("")

    # Diagnostics
    if diagnostics:
        lines.append("BUSINESS DIAGNOSTICS")
        lines.append("-" * 40)
        for key, value in diagnostics.items():
            label = key.replace("_", " ").title()
            if isinstance(value, list):
                lines.append(f"  {label}: {', '.join(value) if value else 'None'}")
            else:
                lines.append(f"  {label}: {value}")
        lines.append("")

    lines.append("=" * 60)
    lines.append("  END OF REPORT — Generated by AI Business Analyst")
    lines.append("=" * 60)

    return "\n".join(lines)
